#!/bin/bash
#
#   Package name:   recapinstaller
#   Author:         Benjamin H. Graham
#
#   Maintainer:     Brent Oswald
#                   Benjamin Graham
#                   Simone Soldateschi
#
#   License:        GPL 2.0
#
#   Homepage:       https://github.com/rackerlabs/recap/
#
#   Installer for Debian and MacOSX currently.
#

#Name: recap
#Requires: sysstat, coreutils, procps, grep, gawk

# Force the shell to exit immediately if something goes wrong
set -e

VERSION="0.9.8"
LOGDIR="/var/log"
MANPATH="/usr/share/man"
SBINDIR="/usr/sbin"
SYSCONFDIR="/etc"
DATADIR="/usr/share"
ROOT_UID=0
OSTYPE=$(uname -s)

if [ "$UID" -ne "$ROOT_UID" ]; then
	echo "You must be root to run this script."
	exit
fi

echo
echo "Installing recap and recaptool to $SBINDIR"
echo

mkdir -p -m0755 $SBINDIR
mkdir -p -m0755 $DATADIR/doc/recap-$VERSION
mkdir -p -m0755 $SYSCONFDIR/cron.d
mkdir -p -m0700 $LOGDIR/recap
mkdir -p -m0700 $LOGDIR/recap/backups
mkdir -p -m0700 $LOGDIR/recap/snapshots
mkdir -p -m0755 $MANPATH/man5
mkdir -p -m0755 $MANPATH/man8

install -m 0755 ../src/recap $SBINDIR/
install -m 0755 ../src/recaplog $SBINDIR/
install -m 0755 ../src/recaptool $SBINDIR/

install -m 0644 ../README.md $DATADIR/doc/recap-$VERSION/
install -m 0644 ../TODO $DATADIR/doc/recap-$VERSION/
install -m 0644 ../CHANGELOG $DATADIR/doc/recap-$VERSION/
install -m 0644 ../COPYING $DATADIR/doc/recap-$VERSION/

gzip src/recap.5
gzip src/recap.8
install -m 0644 recap.5.gz $MANPATH/man5
install -m 0644 recap.8.gz $MANPATH/man8

install -m 0644 ../src/recap.conf $SYSCONFDIR/recap

# if macosx uname -s contains Darwin
if [[ $OSTYPE =~ "Darwin" ]]; then
	install -m 0700 ../util/recap.plist /Library/LaunchDaemons/recap.plist
	launchctl load -w /Library/LaunchDaemons/recap.plist
else
	install -m 0644 ../src/recap.cron $SYSCONFDIR/cron.d/recap
fi


if [ -d $SYSCONFDIR/apache2/conf.d ]; then
	install -m 0644 ../src/recap.httpd.conf $SYSCONFDIR/apache2/conf.d/recap.conf
	echo "To enable webbased stats, see $SYSCONFDIR/apache2/conf.d/recap.conf"
elif [ -d $SYSCONFDIR/httpd/conf.d ]; then
	install -m 0644 ../src/recap.httpd.conf $SYSCONFDIR/httpd/conf.d/recap.conf
	echo "To enable webbased stats, see $SYSCONFDIR/httpd/conf.d/recap.conf"
else
	echo "No /etc/apache2 or /etc/httpd found. Skipping apache configuration installation."
fi

echo
echo "The cron execution of recap is set to run every 10 minutes and at reboot by default."
echo "Edit /etc/cron.d/recap to change cron execution."

echo
echo "recap installation complete."
