.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
.\" Boston, MA 02110-1301 USA.
.\"
.TH RECAP 8 "Aug 18, 2017"
.SH NAME
recap \- dumps periodic information about running applications and resource usage
.SH SYNOPSIS
.BI "recap " [OPTION]
.SH DESCRIPTION
recap is a user\-configurable script that can be run once, or run periodically out of cron or systemd.timers to dump information about running processes and resource usage. It's useful on servers that have periodic, mysterious performance anomalies for tracking down what may be going on at the time of any particular incident.

The values for which reports are generated and how many reports are stored can be overridden in
.IR /etc/recap.conf "."
The output files from the script are written to
.IR BASEDIR "."
.TP
.BR "\-B, \-\-backup"
This will perform a "backup". It will copy the latest log files from the last execution to the "backups" directory inside BASEDIR. The files will be identified by a timestamp in the name.
.TP
.BR "\-S, \-\-snapshot"
This will perform a "snapshot" report. It will generate a set of output files in the "snapshot" directory inside BASEDIR outside of the standard rotation. The files will be identified by a timestamp in the name.
.TP
.BR "\-V, \-\-version"
Print version and exit.
.TP
.SH FILES
.nf
/etc/recap.conf
/etc/cron.d/recap
/usr/lib/systemd/system/recap.{service,timer} \- Unit files for running recap periodically.
/usr/lib/systemd/system/recap\-onboot.{service,timer} \- Unit files for running recap on boot.

.SH "REPORTING BUGS"
Bugs and issues to be submitted via github
<https://github.com/rackerlabs/recap/issues>.

.SH AUTHOR
The recap scripts are maintained by Rackspace, the list of contributors is available at https://github.com/rackerlabs/recap/blob/master/CHANGELOG.md#contributors.
.SH "SEE ALSO"
.BR recap (5),
.BR recaplog (8),
.BR crontab (5),
.BR systemd.timer (5)
